# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'banking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbanking.proto\x12\x07\x62\x61nking\"=\n\x14\x43reateAccountRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0finitial_balance\x18\x02 \x01(\x01\"6\n\x0f\x41\x63\x63ountResponse\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x0e\x42\x61lanceRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"\"\n\x0f\x42\x61lanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x01\":\n\x14UpdateBalanceRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"K\n\x0fTransferRequest\x12\x14\n\x0c\x66rom_account\x18\x01 \x01(\t\x12\x12\n\nto_account\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"#\n\x10TransferResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x13NotificationRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x14NotificationResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xe5\x01\n\x0e\x41\x63\x63ountService\x12H\n\rCreateAccount\x12\x1d.banking.CreateAccountRequest\x1a\x18.banking.AccountResponse\x12?\n\nGetBalance\x12\x17.banking.BalanceRequest\x1a\x18.banking.BalanceResponse\x12H\n\rUpdateBalance\x12\x1d.banking.UpdateBalanceRequest\x1a\x18.banking.BalanceResponse2U\n\x12TransactionService\x12?\n\x08Transfer\x12\x18.banking.TransferRequest\x1a\x19.banking.TransferResponse2f\n\x13NotificationService\x12O\n\x10SendNotification\x12\x1c.banking.NotificationRequest\x1a\x1d.banking.NotificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEACCOUNTREQUEST']._serialized_start=26
  _globals['_CREATEACCOUNTREQUEST']._serialized_end=87
  _globals['_ACCOUNTRESPONSE']._serialized_start=89
  _globals['_ACCOUNTRESPONSE']._serialized_end=143
  _globals['_BALANCEREQUEST']._serialized_start=145
  _globals['_BALANCEREQUEST']._serialized_end=181
  _globals['_BALANCERESPONSE']._serialized_start=183
  _globals['_BALANCERESPONSE']._serialized_end=217
  _globals['_UPDATEBALANCEREQUEST']._serialized_start=219
  _globals['_UPDATEBALANCEREQUEST']._serialized_end=277
  _globals['_TRANSFERREQUEST']._serialized_start=279
  _globals['_TRANSFERREQUEST']._serialized_end=354
  _globals['_TRANSFERRESPONSE']._serialized_start=356
  _globals['_TRANSFERRESPONSE']._serialized_end=391
  _globals['_NOTIFICATIONREQUEST']._serialized_start=393
  _globals['_NOTIFICATIONREQUEST']._serialized_end=431
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=433
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=471
  _globals['_ACCOUNTSERVICE']._serialized_start=474
  _globals['_ACCOUNTSERVICE']._serialized_end=703
  _globals['_TRANSACTIONSERVICE']._serialized_start=705
  _globals['_TRANSACTIONSERVICE']._serialized_end=790
  _globals['_NOTIFICATIONSERVICE']._serialized_start=792
  _globals['_NOTIFICATIONSERVICE']._serialized_end=894
# @@protoc_insertion_point(module_scope)
